const projects = [
  {
    slug: 'pattern-tool',
    title: 'Vector Pattern Tool',
    tags: ['SVG', 'Canvas'],
    color: '#1a1a2e',
    gif: 'gifs/pattern-tool.gif',
    url: 'works/pattern-tool.html',
  },
  {
    slug: 'maschera-sonora',
    title: 'Girandola Sonora',
    tags: ['SVG', 'Audio'],
    color: '#2d1b2e',
    gif: 'gifs/maschera-sonora.gif',
    url: 'works/maschera-sonora.html',
  },
  {
    slug: 'bubble-pop',
    title: 'Bubble Pop',
    tags: ['Canvas', 'Hand Tracking', 'TensorFlow'],
    color: '#1a2e2e',
    gif: 'gifs/bubble-pop.gif',
    url: 'works/bubble-pop.html',
  },
  {
    slug: 'tipografia-cinetica',
    title: 'Tipografia Cinetica',
    tags: ['Canvas', 'Typography'],
    color: '#2e1a1a',
    gif: 'gifs/tipografia-cinetica.gif',
    url: 'works/tipografia-cinetica.html',
  },
  {
    slug: 'salame-cioccolato',
    title: 'Salame di Cioccolato',
    tags: ['Ricetta', 'Design'],
    color: '#3b1f0a',
    gif: 'gifs/salame-cioccolato.gif',
    url: 'works/salame-cioccolato.html',
  },
];

const content = {
  it: {
    heroTitle: 'MELISSA COCO',
    heroSub: 'WS INTERACTION DESIGN & AI',
    heroDate: '18 - 22 MAGGIO 2025',
    heroCta: 'Vedi i lavori',
    worksTitle: 'Lavori',
    aboutTitle: 'ABOUT',
    aboutMelissa: 'Sono una designer e creative coder con una fame insaziabile di sperimentazione. Il mio lavoro si muove tra interaction design, motion graphics e generative art — con l\'obbiettivo di creare esperienze visive che parlano, emozionano e, perché no, stupiscono. Ogni progetto è un\'occasione per mescolare codici, colori e idee, trasformando concetti in linguaggi visivi vivi.',
    aboutAbadir: 'ABADIR è un\'accademia che non si accontenta del già visto. Qui il design si insegna come pratica viva, tra laboratorio e pensiero critico. È il luogo dove ho imparato a guardare oltre lo schermo — a interrogare la forma, la materia, il movimento. Un posto che spinge a rompere le regole, ma prima a conoscerle bene.',
    aboutWs: 'Il workshop \'Interaction Design & AI\' è stato un\'esplosione di creatività collettiva. Per cinque giorni abbiamo progettato, prototipato e fallito — per poi riprovare, meglio. Tra algortimi generativi, motion design e interazioni in tempo reale, ogni partecipante ha costruito qualcosa di unico. Questo portfolio è il diario di bordo di quel viaggio.',
    contactTitle: 'Contatti',
    contactEmail: 'm.coco@abadir.net',
    navWorks: 'Lavori',
    navAbout: 'Chi sono',
    navContact: 'Contatti',
    langBtn: 'EN',
  },
  en: {
    heroTitle: 'MELISSA COCO',
    heroSub: 'WS INTERACTION DESIGN & AI',
    heroDate: '18 - 22 MAGGIO 2025',
    heroCta: 'View my work',
    worksTitle: 'Works',
    aboutTitle: 'ABOUT',
    aboutMelissa: 'I\'m a designer and creative coder with an insatiable hunger for experimentation. My work lives at the intersection of interaction design, motion graphics, and generative art — creating visual experiences that speak, move, and surprise. Every project is a chance to blend code, color, and ideas into living visual languages.',
    aboutAbadir: 'ABADIR is an academy that refuses the ordinary. Here design is taught as a living practice — between hands-on workshops and critical thinking. It\'s where I learned to look beyond the screen, questioning form, material, and movement. A place that pushes you to break the rules — but first, to know them inside out.',
    aboutWs: 'The \'Interaction Design & AI\' workshop was an explosion of collective creativity. For five days we designed, prototyped, failed — then tried again, better. Between generative algorithms, motion design, and real-time interactions, each participant built something unique. This portfolio is the logbook of that journey.',
    contactTitle: 'Contact',
    contactEmail: 'melissa@email.com',
    navWorks: 'Works',
    navAbout: 'About',
    navContact: 'Contact',
    langBtn: 'IT',
  },
};
