const projects = [
  {
    slug: 'pattern-tool',
    title: 'Vector Pattern Tool',
    tags: ['SVG', 'Canvas'],
    color: '#1a1a2e',
    gif: 'gifs/pattern-tool.gif',
    url: 'works/pattern-tool.html',
  },
  {
    slug: 'maschera-sonora',
    title: 'Girandola Sonora',
    tags: ['SVG', 'Audio'],
    color: '#2d1b2e',
    gif: 'gifs/maschera-sonora.gif',
    url: 'works/maschera-sonora.html',
  },
  {
    slug: 'bubble-pop',
    title: 'Bubble Pop',
    tags: ['Canvas', 'Hand Tracking', 'TensorFlow'],
    color: '#1a2e2e',
    gif: 'gifs/bubble-pop.gif',
    url: 'works/bubble-pop.html',
  },
  {
    slug: 'tipografia-cinetica',
    title: 'Tipografia Cinetica',
    tags: ['Canvas', 'Typography'],
    color: '#2e1a1a',
    gif: 'gifs/tipografia-cinetica.gif',
    url: 'works/tipografia-cinetica.html',
  },
  {
    slug: 'salame-cioccolato',
    title: 'Salame di Cioccolato',
    tags: ['Ricetta', 'Design'],
    color: '#3b1f0a',
    gif: 'gifs/salame-cioccolato.gif',
    url: 'works/salame-cioccolato.html',
  },
];

const content = {
  it: {
    heroTitle: 'MELISSA COCO',
    heroSub: 'WS INTERACTION DESIGN & AI',
    heroDate: '18 - 22 MAGGIO 2025',
    heroCta: 'Vedi i lavori',
    worksTitle: 'Lavori',
    aboutTitle: 'ABOUT',
    aboutMelissa: 'Sono una studentessa di Graphic Design e Media Digitali presso l\'Accademia Abadir, e questo portfolio racconta il mio percorso — fatto di curiosità, errori, esperimenti e tanta voglia di imparare. Non mi definisco una designer, ma qualcuna che sta costruendo il proprio sguardo: tra lezioni, progetti, workshop e nottate a inseguire un\'idea. Mi affascina la possibilità di mescolare codici, colori e concetti per dare forma a qualcosa che prima non c\'era. Il mio lavoro si muove tra interaction design, motion graphics e generative art — con l\'obiettivo di creare esperienze visive che parlano, emozionano e, perché no, stupiscono. Ogni progetto è un\'occasione per imparare qualcosa di nuovo, e ogni errore un gradino in più verso un linguaggio visivo tutto mio.',
    aboutAbadir: 'ABADIR è un\'accademia che non si accontenta del già visto. Qui il design si insegna come pratica viva, tra laboratorio e pensiero critico. È il luogo dove ho imparato a guardare oltre lo schermo — a interrogare la forma, la materia, il movimento. Un posto che spinge a rompere le regole, ma prima a conoscerle bene. Fondata nel 1998, Abadir è un polo creativo che integra formazione, produzione artistica e ricerca. Diplomarsi qui significa uscire con un bagaglio che va oltre la tecnica: si impara a pensare il design come strumento critico, capace di leggere e trasformare la realtà.',
    aboutWs: 'Sito sviluppato durante il workshop "No brain, No Gain", tenuto da whateverDev (Andrea Maffei & Rocco Lorenzo Modugno),\n18-22 Maggio 2026, all\'interno dei corsi:\n\nInteraction Design 2\nProf. Alessia Scudieri\n\nInteraction Design 3\nProf. Andrea Leonardi\nProf. Marcantonio D\'Antoni\n\nABADIR\nAccademia di Design e Comunicazione Visiva\nSant\'Agata li Battiati CT\nAA 2025-26',
    contactTitle: 'Contatti',
    contactCopy: 'Se vuoi collaborare, parlarmi di un progetto o semplicemente fare due chiacchiere, scrivimi pure. Sono sempre aperta a idee nuove e confronti.',
    contactEmail: 'm.coco@abadir.net',
    navWorks: 'Lavori',
    navAbout: 'Chi sono',
    navContact: 'Contatti',
    langBtn: 'EN',
  },
  en: {
    heroTitle: 'MELISSA COCO',
    heroSub: 'WS INTERACTION DESIGN & AI',
    heroDate: '18 - 22 MAY 2025',
    heroCta: 'View my work',
    worksTitle: 'Works',
    aboutTitle: 'ABOUT',
    aboutMelissa: 'I\'m a student of Graphic Design and Digital Media at Abadir Academy, and this portfolio tells my journey — made of curiosity, mistakes, experiments, and a strong desire to learn. I don\'t call myself a designer yet, but someone who\'s building their own perspective: through lessons, projects, workshops, and late nights chasing an idea. I\'m fascinated by the possibility of blending code, color, and concepts to shape something that didn\'t exist before. My work moves between interaction design, motion graphics, and generative art — aiming to create visual experiences that speak, move, and maybe even surprise. Every project is a chance to learn something new, and every mistake is one more step toward a visual language that\'s entirely my own.',
    aboutAbadir: 'ABADIR is an academy that refuses the ordinary. Here design is taught as a living practice — between hands-on workshops and critical thinking. It\'s where I learned to look beyond the screen, questioning form, material, and movement. A place that pushes you to break the rules — but first, to know them inside out. Founded in 1998, Abadir is a creative hub that blends education, artistic production, and research. Graduating here means coming out with a mindset that goes beyond technique: learning to see design as a critical tool, capable of reading and transforming reality.',
    aboutWs: 'Website developed during the "No brain, No Gain" workshop, led by whateverDev (Andrea Maffei & Rocco Lorenzo Modugno),\n18-22 May 2026, within the courses:\n\nInteraction Design 2\nProf. Alessia Scudieri\n\nInteraction Design 3\nProf. Andrea Leonardi\nProf. Marcantonio D\'Antoni\n\nABADIR\nAcademy of Design and Visual Communication\nSant\'Agata li Battiati CT\nAA 2025-26',
    contactTitle: 'Contact',
    contactCopy: 'If you want to collaborate, talk about a project, or just have a chat, feel free to reach out. I\'m always open to new ideas and conversations.',
    contactEmail: 'melissa@email.com',
    navWorks: 'Works',
    navAbout: 'About',
    navContact: 'Contact',
    langBtn: 'IT',
  },
};
